### PR TITLE
Copy soundfonts after finishing the build

### PR DESCRIPTION
**Pull request by jofemodo**

### CODE REVIEW

**Comment by jofemodo** [comment]
Hi @guysoft !

As we are really close, i would like to start including soundfonts in the build.
Perhaps it will be better if we could have 2 different builds:

+ The automatic (nightly) with a minimum soundfont set for testing
+ The manual for official releases, that includes a full set of soundfonts

What is the best way of achieving this? CustomPiOS variants? Or better to have 2 different modules?
Or perhaps having 2 projects in Jenkins and using an environment variable for configuring this?

**Comment by guysoft** [comment]
Hey, this assumes you have the soundfonts copied from somewhere - I suggest that is added to the docs and it needs to be a command before the build.

**Comment by jofemodo** [comment]
Yes. I've copied the files by hand.
As it's not overwriten by the "git pull", i don't think is needed to do that on every build. The soundfonts are more than 3GB ... We could do an "if [ ! -d blablabla ]" ...

Also, is a problem to do it the "unpack" call after the building process? I hope no ...

Regards,

**Comment by jofemodo** [comment]
Regarding the copying of soundfont files ... is really needed to make a hard-copy or it would work with a soft link?

**Comment by jofemodo** [comment]
I'm cancelling this PR and will create a new one ...

**Comment by guysoft** [comment]
1. You need a hard-copy. Otherwise it would just copy the symlink. Those are technically files too.
2. You need to add to the instructions [here](https://github.com/guysoft/ZynthianOS#build-raspbian--debian--ubuntu)  where the files should be placed.

**Pull request closed without merging**
