### PR TITLE
Copy soundfonts after finishing the build

### PR DESCRIPTION
**Pull request by jofemodo**
I'm copying (if needed) the soundfonts to filesystem before start the build, from jenkins script.

### CODE REVIEW

**Comment by guysoft** [comment]
Can you say where the soundfonts shipped with Zynthian come from?
Imagine if someone wants to make their own build where do the soundfonts come from. Its also a license issue to know where they all come from.

**Comment by guysoft** [comment]
Still waiting for the question "where are the files shipped with Zynthian actually from?"

You can also just host them yourself, but you should say where they come from.

**Comment by jofemodo** [comment]
Hi @guysoft,

The soundfonts included in the "official" Zynthian SD comes from many fonts. There is a list of links in the wiki:

http://wiki.zynthian.org/index.php/Sound_Fonts#Soundfont_Collection_Links

I compiled this list 2-3 years ago and now it's difficult to say the origin of every font because when i compiled the collection, i renamed many instruments for having a "more or less" coherent naming convention across the library.

I remember that one of the more used sources was this one:

http://www.bandshed.net/sounds/sfz/

But many other sources were used too. 

Also, many of the soundfonts from the links above, included bandshed, comes from other compilations  by people that is sharing their collections, probably renamed, and so on ...

Of course, you can open every "sfz" file and try ot trace-back the origin, but many soundfonts have no comments, copyright notes or authoring marks.

I think the best option is to say that the soundfonts comes from several free repositories, listed on the zynthian wiki.

Anyway, that's not part of ZynthianOS itself. The soundfonts are copied by the Jenkins process. I don't understand where do you want to put this info ...

Cheers
Kind Regards,

**Comment by guysoft** [comment]
So I suggest hosting them on zynthian.org and point there for where to download.
You might have in theory a license violation there, I am not sure how to check without knowing who made what.

You could also have them in folders per Zynthian version. So people can go back and you have an archive.

**Comment by jofemodo** [comment]
The official Zynthian SD always has included a soundfont collection and i wouldn't like to remove it. People like to have something to play with when testing LinuxSampler or FluidSynth engines for first time.

Also, i don't like the approach "all information is propietary by default", as it adds a lot of burocracy and complexity and is against nature. Rather i prefer the "all available information is free and can be shared" approach, that is "nature law" and adds "zero burocracy" ;-)

**Comment by guysoft** [comment]
That's your call,

But I would urge to not require the Zynthian image build to have a step
which involves taking files manually from another image.
I'd rather have a single wget command for a zip file or git repo that
hosted in an accessible location. Git would have the advantage that version
control would let you know what was added to the image when, tagging for
zynthian releases etc.

**Comment by guysoft** [comment]
Hey, should I pull this?
Or are you using a different repo now?
@jofemodo

**Comment by jofemodo** [comment]
Yes. Pull it.

Thanks!

**Pull request merged**
